cities:
- active: true
  code: PHIL
  kalshi_market_prefix: KXHIGHPHIL
  kalshi_market_prefix_low: KXLOWPHIL
  lat: 39.8722
  lon: -75.2408
  name: Philadelphia
  nws_station_id: KPHL
  timezone: America/New_York
- active: true
  code: CHI
  kalshi_market_prefix: KXHIGHCHI
  kalshi_market_prefix_low: KXLOWCHI
  lat: 41.9742
  lon: -87.9073
  name: Chicago
  nws_station_id: KORD
  timezone: America/Chicago
- active: true
  code: DEN
  kalshi_market_prefix: KXHIGHDEN
  kalshi_market_prefix_low: KXLOWDEN
  lat: 39.8561
  lon: -104.6737
  name: Denver
  nws_station_id: KDEN
  timezone: America/Denver
- active: true
  code: AUS
  kalshi_market_prefix: KXHIGHAUS
  kalshi_market_prefix_low: KXLOWAUS
  lat: 30.1944
  lon: -97.67
  name: Austin
  nws_station_id: KAUS
  timezone: America/Chicago
- active: true
  code: MIA
  kalshi_market_prefix: KXHIGHMIA
  kalshi_market_prefix_low: KXLOWMIA
  lat: 25.7959
  lon: -80.287
  name: Miami
  nws_station_id: KMIA
  timezone: America/New_York
- active: true
  code: NOLA
  kalshi_market_prefix: KXHIGHNOLA
  kalshi_market_prefix_low: KXLOWNOLA
  lat: 29.9911
  lon: -90.2589
  name: New Orleans
  nws_station_id: KMSY
  timezone: America/Chicago
- active: true
  code: BOS
  kalshi_market_prefix: KXHIGHBOS
  kalshi_market_prefix_low: KXLOWBOS
  lat: 42.3643
  lon: -71.0051
  name: Boston
  nws_station_id: KBOS
  timezone: America/New_York
- active: true
  code: NY
  kalshi_market_prefix: KXHIGHNY
  kalshi_market_prefix_low: KXLOWNY
  lat: 40.7829
  lon: -73.9654
  name: New York
  nws_station_id: KNYC
  timezone: America/New_York
